### ISSUE TITLE
Unsafe in high concurrency

### ISSUE THREAD

**Issue by aidy-automan** [sony/sonyflake#12]
**this is my code** 
```
for i:=0;i<100;i++ {
	go func() {
		flake := sonyflake.NewSonyflake(sonyflake.Settings{})
                pid, _ = flake.NextID()
		pidStr := strconv.FormatInt(int64(pid),10)
		t := utils.Md5(pidStr + time.Now().Format("2006-01-02 15:04:05"))
		session_key := t
		openid := t
		tpRes, _ := models.PersionLogin(int64(pid), t, session_key, openid)
	}()
}
```
**result, pid has repeat**

1 | pid | 275026772355976047 |   |   | 2019-11-11 15:45:30
-- | -- | -- | -- | -- | --
2 | pid | 275026772355976047 |   |   | 2019-11-11 15:45:30
3 | pid | 275026772355976047 |   |   | 2019-11-11 15:45:30
4 | pid | 275026772389530479 |   |   | 2019-11-11 15:45:31
5 | pid | 275026772305644399 |   |   | 2019-11-11 15:45:31
6 | pid | 275026772355976047 |   |   | 2019-11-11 15:45:30
7 | pid | 275026772255312751 |   |   | 2019-11-11 15:45:30
8 | pid | 275026772070763375 |   |   | 2019-11-11 15:45:31
9 | pid | 275026772137872239 |   |   | 2019-11-11 15:45:31
10 | pid | 275026772272089967 |   |   | 2019-11-11 15:45:30
...

**Comment by YoshiyukiMineo** [comment]
> flake := sonyflake.NewSonyflake(sonyflake.Settings{})

This is because you create a new Sonyflake instance every time.
Please use the same Sonyflake instance in the loop.
