### ISSUE TITLE
is it safe for PostgreSQL bigint

### ISSUE THREAD

**Issue by Kulak** [sony/sonyflake#15]
I see that it leaves most significant bit unused.  That shall make it safe for use with 64 bit signed integer, because it will never go into the negative range from DB perspective (and will stay sortable).

Am I reading it right?

**Comment by YoshiyukiMineo** [comment]
Yes, it is safe to use Sonyflake IDs as 64 bit signed integer like Java `long` type.

**Comment by Kulak** [comment]
It is an excellent project.  Thank you
