### ISSUE TITLE
Is it possible to have a method which returns the timestamp/metadata used to create the sonyflake?

### ISSUE THREAD

**Issue by mmacheerpuppy** [sony/sonyflake#16]
Hi,

Thanks for the library. It would be nice to get the time{} struct the sonyflake is based off so that implementing services can prevent drift between recording current time and time allocated to the sonyFlake.

Please let me know if this is something you can do.

Cheers!

**Comment by YoshiyukiMineo** [comment]
You can get the timestamp from a Sonyflake ID in the following way:
1. `Decompose` a Sonyflake ID and get the time value in units of 10 msec from the returned map.
https://github.com/sony/sonyflake/blob/master/sonyflake.go#L168
2. Multiply the time value by 10 msec and add the elasped time to your `StartTime`
https://github.com/sony/sonyflake/blob/master/sonyflake.go#L38

**Comment by titpetric** [comment]
@YoshiyukiMineo would you accept a PR to add a function to SonyFlake{}, that would take an uint64 (the generated sonyflake ID), and return a time.Time from it?

**Comment by mmacheerpuppy** [comment]
That's great @titpetric I think that's a seperate but please link to this issue if you do make a PR so people can track! I'm closing this for now!
