### ISSUE TITLE
i think the sleepTime func is wrong.

### ISSUE THREAD

**Issue by woshihuo12** [sony/sonyflake#28]
`func sleepTime(overtime int64) time.Duration {
	return time.Duration(overtime)*10*time.Millisecond -
		time.Duration(time.Now().UTC().UnixNano()%sonyflakeTimeUnit)*time.Nanosecond
}`

i think overtime is no need minus the now time, so i think below is right:
`func sleepTime(overtime int64) time.Duration {
	return time.Duration(overtime) * 10 * time.Millisecond
}`

**Comment by YoshiyukiMineo** [comment]
> i think overtime is no need minus the now time, so i think below is right:

The Now time is not subtracted in sleepTime.
Only the fraction against Sonyflake's unit time (10 msec) is subtracted in it:
`time.Now().UTC().UnixNano()%sonyflakeTimeUnit`
