### ISSUE TITLE
So if each EC2 instance has a unique private IP address in AWS VPC, the lower 16 bits of the address is also unique

### ISSUE THREAD

**Issue by rush24** [sony/sonyflake#30]
> So if each EC2 instance has a unique private IP address in AWS VPC, the lower 16 bits of the address is also unique

why?

**Comment by YoshiyukiMineo** [comment]
See https://docs.aws.amazon.com/vpc/latest/userguide/configure-your-vpc.html#vpc-sizing
> When you create a VPC, you must specify an IPv4 CIDR block for the VPC. The allowed block size is between a /16 netmask (65,536 IP addresses) and /28 netmask (16 IP addresses).

The above is applicable to VPC with IPv4. Previously AWS VPC supported only IPv4. But recently it also supports IPv6.
