### ISSUE TITLE
Question: uint64 or int64?

### ISSUE THREAD

**Issue by theory** [sony/sonyflake#31]
From the README, sonyflake uses 63 bits. This aligns with the design of  [Snowflake ID](https://en.wikipedia.org/wiki/Snowflake_ID), which is specifically designed to fit in a signed integer:

> Snowflakes are 64 [bits](https://en.wikipedia.org/wiki/Bit). (Only 63 are used to fit in a [signed integer](https://en.wikipedia.org/wiki/Two%27s_complement).)

I notice that sonyflake returns uint64 rather than int64:

https://github.com/sony/sonyflake/blob/848d664ceea4c980874f2135c85c42409c530b1f/sonyflake.go#L86

Should it return int64, instead?

I assume not since it has been around for a while. If that's correct, perhaps some documentation could be added to describe how to safely convert the value into an int64 so that it might more easily be used in databases that don't support uint?

**Comment by smithyj** [comment]
The NextID return should return int64，because the result max is int64 length

**Comment by YoshiyukiMineo** [comment]
Thank you for your feedback!
I think it is better to keep the interface for the compatibility. I have added a note instead:
https://github.com/sony/sonyflake/commit/3719d006ac3b5aa6d2beb9739a1d1e637ec3d53f
