### ISSUE TITLE
How do you use the timestamp extracted from the id?

### ISSUE THREAD

**Issue by dancb10** [sony/sonyflake#33]
Seems like when I try to use the sonyflake.Decompose on the generated ID, I get a timestamp which is similar to `24869724975`. How can I convert this into an epoch timestamp so a I can sort by date in the DB? What I need is to be able to generate a timestamp from the current date and compare to the timestamps stored in the DBs as primary keys

**Comment by YoshiyukiMineo** [comment]
Please see https://github.com/sony/sonyflake/issues/16#issuecomment-597412159.

**Comment by YoshiyukiMineo** [comment]
I have added the function to extract the elapsed time from the given Sonyflake ID:
https://github.com/sony/sonyflake/pull/35/files#diff-83e27b61feae6236407536ea0184cca96f333a4a3f7e2983cdb28e0c183aa770R169
