### ISSUE TITLE
Can't create sonyflake in the `init()` function in ubuntu.

### ISSUE THREAD

**Issue by ZenkieBear** [sony/sonyflake#55]
I have a init function:

```go
func init() {
	sf = sonyflake.NewSonyflake(sonyflake.Settings{
		StartTime: time.Now(),
	})
	if sf == nil {
		panic("sonyflake is not create")
	}
	fmt.Println("Sonyflake is initialized")
}
```

I works right on my macOS(M2) system.

Now I have to compile it to `linux/amd64` architecture, when I put the compiled executable program to the Ubuntu system, it can't not be run, and into the panic("sonyflake is not create").

So that means *sonyflake* is not compatible with linux/amd64 architecture.

**Comment by jpduckwo** [comment]
@ZenkieBear what was the issue? We are seeing the same thing, we're thinking it's something to do with the docker build images we are using

**Comment by ZenkieBear** [comment]
> @ZenkieBear what was the issue? We are seeing the same thing, we're thinking it's something to do with the docker build images we are using

That's a good solution, but now we are using crossing-compile to adapter different OS and platforms.

**Comment by NidhoogJX** [comment]
as a result of[https://github.com/sony/sonyflake/issues/57](url)
